<!Doctype html>
<html>
<head>
	<title>
		NIIT H.W.
	</title>
	<script type="text/javascript">
		var name;
		var gender;
	
		name=prompt("Please enter your name:")
		gender=prompt("Please enter your gender:")
		
		if(gender==male||Male)
				{
					alert("Hello Mr."+name);
				}
		
		if(gender==female||Female)
				{
					alert("Hello Mrs."+name);
				}
		
		else
		{
			alert("Please enter correct values");
		}
	</script>
</head>
</html>